name: widget_book
description: "lego is all you need"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/lego

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  june_flow_util:
  device_preview_minus:
  flutter_svg:
  gap:
  styled_widget:
  modal_bottom_sheet:
  keyboard_attachable:
  flutter_zoom_drawer:
  flutter_screenutil:
  bot_toast:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  netflix_main_view_lego:
  screenutil_lego:
  bot_toast_lego:

flutter:
  assets:
    - assets/lego/netflix_main_view_lego/
  uses-material-design: true