name: widget_book
description: "lego is all you need"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/lego

version: 1.0.0+2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  june_flow_util:
  device_preview_minus:
  flutter_svg:
  gap:
  styled_widget:
  modal_bottom_sheet:
  keyboard_attachable:
  flutter_zoom_drawer:
  flutter_screenutil:
  bot_toast:
  june:
  tuple: ^2.0.2
  flutter_inappwebview:
  super_cupertino_navigation_bar_for_my_self:
  url_launcher: ^6.3.0
  auto_size_text:
  flutter_color:
  infinite_listview:
  animated_notch_bottom_bar:
  dot_navigation_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  netflix_main_view_lego:
  screenutil_lego:
  bot_toast_lego:
  june_lego:
  toast_view_lego:
  chrome_style_browser_lego:
  theme_config_lego:
  basic_bottom_navigation_view_lego:
  widget_binding_lego:
  simple_memo_lego:
  favorite_button_lego:
  navigation_rail_view_lego:
  insta_profile_page_lego:
  insta_style_main_feed_lego:
  kakao_chatroom_list_lego:
  alert_feed_page_lego:
  insta_style_feed_lego:
  login_view2_lego:
  login_view3_lego:
  toss_intro_page_lego:
  login_and_register_page_lego:
  insta_personal_page_lego:
  kakao_style_friend_feed_lego:
  chatgpt_appbar_view_lego:
  facebook_appbar_view_lego:
  youtube_appbar_view_lego:
  insta_app_bar_view_lego:
  insta_style_bottom_navi2_lego:
  animated_notch_bottom_bar_view_lego:
  spotify_bottom_navi_lego:
  google_drive_bottom_navi_lego:
  youtube_bottom_navi_view_lego:
  insta_style_bottom_navigation_bar_lego:
  dot_navigation_bar_basic_lego:
  defaul_tap_bar_lego:
  facebook_tapbar_view_lego:


flutter:
  assets:
    - assets/lego/insta_style_bottom_navigation_bar_lego/
    - assets/lego/spotify_bottom_navi_lego/
    - assets/lego/insta_style_bottom_navi2_lego/
    - assets/lego/insta_app_bar_view_lego/
    - assets/lego/youtube_appbar_view_lego/
    - assets/lego/kakao_style_friend_feed_lego/
    - assets/lego/insta_personal_page_lego/
    - assets/lego/login_and_register_page_lego/
    - assets/lego/toss_intro_page_lego/
    - assets/lego/basic_bottom_navigation_view_lego/
    - assets/lego/netflix_main_view_lego/
    - assets/pubdev.svg
    - assets/lego/login_view3_lego/
    - assets/lego/login_view2_lego/
    - assets/lego/insta_style_feed_lego/
    - assets/lego/alert_feed_page_lego/
    - assets/lego/insta_style_main_feed_lego/
    - assets/lego/insta_profile_page_lego/
  uses-material-design: true